[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "corepack enable && pnpm install --legacy-peer-deps && pnpm run build"
  publish = ".next" # change to "build" or "dist" depending on your framework
